from __future__ import annotations
import json
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT=Path(__file__).resolve().parent;FINAL=ROOT/'artifacts/final';FIG=FINAL/'paper-v3-figures';FIG.mkdir(parents=True,exist_ok=True)
PAPER=Path('/Users/chchou/Downloads/MCP_ToolProof_KIISC_3페이지_논문.pdf');BLUE='#173A63';CYAN='#11A8A5';ORANGE='#F28E2B';LIGHT='#EEF3F8'
FONT='/System/Library/Fonts/Supplemental/AppleGothic.ttf';pdfmetrics.registerFont(TTFont('K',FONT));pdfmetrics.registerFont(TTFont('KB',FONT));plt.rcParams['font.family']='Apple SD Gothic Neo';plt.rcParams['axes.unicode_minus']=False
S=getSampleStyleSheet();S['Title'].fontName='KB';S['Title'].fontSize=16.2;S['Title'].leading=19.5;S.add(ParagraphStyle(name='B',fontName='K',fontSize=10.0,leading=14.2,wordWrap='CJK',alignment=TA_JUSTIFY,spaceAfter=3.0));S.add(ParagraphStyle(name='T',fontName='K',fontSize=7.1,leading=9.0,wordWrap='CJK'));S.add(ParagraphStyle(name='H',fontName='KB',fontSize=12.5,leading=15.2,textColor=colors.HexColor(BLUE),spaceBefore=5,spaceAfter=2.5));S.add(ParagraphStyle(name='H2',fontName='KB',fontSize=10.5,leading=13.0,textColor=colors.HexColor(BLUE),spaceBefore=4,spaceAfter=2));S.add(ParagraphStyle(name='C',fontName='K',fontSize=8.5,leading=10.5,alignment=TA_CENTER));S.add(ParagraphStyle(name='Cap',fontName='K',fontSize=7.2,leading=9.0,alignment=TA_CENTER,wordWrap='CJK'))
def P(x,s='B'):return Paragraph(str(x),S[s])
def table(rows,widths):
 t=Table([[P(x,'T') for x in r] for r in rows],colWidths=widths,repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor(BLUE)),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#AAB6C3')),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor(LIGHT)]),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),2),('RIGHTPADDING',(0,0),(-1,-1),2),('TOPPADDING',(0,0),(-1,-1),1.4),('BOTTOMPADDING',(0,0),(-1,-1),1.4)]));return t
def save(name):p=FIG/name;plt.tight_layout();plt.savefig(p,dpi=240,bbox_inches='tight',facecolor='white');plt.close();return str(p)
def footer(c,d):c.saveState();c.setFont('K',6.5);c.setFillColor(colors.HexColor('#667085'));c.drawCentredString(A4[0]/2,6*mm,str(d.page));c.restoreState()

def make_figures(a,r,sensor):
 labels=['Manifest','Response','Trajectory-lite','Attestation','Learned','Frozen contract'];defs=['manifest_pin','response_schema','trajectory_lite','canonical_attestation','learned_relation','toolproof_frozen']
 hold_keys={'manifest_pin':'manifest_pin','response_schema':'response_schema','trajectory_lite':'connor_lite_trajectory','canonical_attestation':'canonical_action_attestation','learned_relation':'learned_effect_relation','toolproof_frozen':'toolproof_frozen'}
 cal=[sensor['metrics'][k]['recall'] for k in defs];hold=[r['external_holdout']['defenses'][hold_keys[k]]['recall'] for k in defs]
 x=np.arange(6);w=.34;plt.figure(figsize=(9.3,3.5));plt.bar(x-w/2,cal,w,label='센서 양성대조군',color=ORANGE);plt.bar(x+w/2,hold,w,label='외부-schema hold-out',color=BLUE);plt.xticks(x,labels,rotation=10);plt.ylabel('Recall');plt.ylim(0,1.05);plt.legend(ncol=2);plt.title('그림 1. 센서가 관측하는 공격에서는 0이 아니며, corpus에 따라 탐지 범위가 달라진다')
 for i,v in enumerate(cal):plt.text(i-w/2,v+.02,f'{v:.2f}',ha='center',fontsize=7)
 for i,v in enumerate(hold):plt.text(i+w/2,v+.02,f'{v:.2f}',ha='center',fontsize=7)
 f1=save('coverage.png')
 attacks=sorted(k for k in r['external_holdout']['by_attack'] if k!='none');mat=np.array([[r['external_holdout']['by_attack'][x][d]['recall'] for x in attacks] for d in ['connor_lite_trajectory','learned_effect_relation','toolproof_frozen']]);plt.figure(figsize=(9.2,2.8));plt.imshow(mat,vmin=0,vmax=1,cmap='YlGnBu',aspect='auto');plt.colorbar(label='Recall');plt.yticks(range(3),['Trajectory-lite','Learned relation','Frozen contract']);plt.xticks(range(len(attacks)),[x.replace('_','\n') for x in attacks],fontsize=7)
 for i in range(3):
  for j in range(len(attacks)):plt.text(j,i,f'{mat[i,j]:.2f}',ha='center',va='center',fontsize=8,color='white' if mat[i,j]>.65 else 'black')
 plt.title('그림 2. 공격 계열별 Recall: 집계 F1보다 구조적 실패가 직접 보인다');f2=save('family.png')
 prev=[.5,.1,.01,.001];x=np.arange(4);w=.32;plt.figure(figsize=(9.2,3.0))
 pre=json.loads((FINAL/'preregistered-metrics.json').read_text())
 for j,k in enumerate(['toolproof','toolproof_v2']):
  y=[next(q['f1'] for q in pre['defenses'][k]['prevalence'] if q['prevalence']==z) for z in prev];plt.bar(x+(j-.5)*w,y,w,label='v1' if j==0 else 'v2',color=BLUE if j==0 else CYAN)
 plt.xticks(x,['1:1','1:9','1:99','1:999']);plt.ylim(0,1.05);plt.ylabel('F1');plt.xlabel('공격:정상');plt.legend();plt.title('그림 3. 저유병률에서는 FPR이 배치 결정을 지배한다');f3=save('prevalence.png')
 return f1,f2,f3

def main():
 a=json.loads((FINAL/'analysis.json').read_text());r=json.loads((FINAL/'robustness-analysis.json').read_text());pre=json.loads((FINAL/'preregistered-metrics.json').read_text());sensor=json.loads((FINAL/'sensor-coverage-analysis.json').read_text());f1,f2,f3=make_figures(a,r,sensor);o=r['original_cluster_robust'];eh=r['external_holdout'];oa=r['oauth_async'];v1=o['toolproof'];v2=o['toolproof_v2']
 story=[P('MCP 외부효과 변조에 대한 동결 의미계약의 탐지 경계 측정','Title'),P('Measuring the Detection Boundary of Frozen Semantic Contracts for MCP External-Effect Manipulation','C'),P('익명 심사용 원고','C'),Spacer(1,2*mm),P('<b>요약</b>  1,008개 의미 조건에서 manifest·응답을 유지한 외부효과 변조를 측정하고, 공식 MCP schema를 동결한 8모델 hold-out과 센서 양성대조군 5,400회를 추가했다. 동결 계약은 직접 필드·개수·종류 변조에는 유효했지만 간접참조 공격 Recall은 사실상 0이었다. 정상 실행에서 학습한 단순 값 관계와 hold-out Recall·F1이 같아, 계약 엔지니어링의 이점은 schema completeness와 명시적 정책 설명에 한정됐다. 또한 공격:정상=1:999에서 v1/v2 F1은 0.724/0.264로 역전되고 receipt p95는 301.7ms였다. 결론적으로 동결 값-의미 계약은 직접 변조 센서이지 일반 행동 증명이 아니며, 간접참조·observer 독립성·운영 유병률이 배치를 결정한다.'),
 P('1. 서론','H'),P('MCP tool의 manifest와 정상형 응답은 실제 side effect의 수신자·범위·개수를 보장하지 않는다[1]. 기존 연구는 tool poisoning[2], runtime defense[3], intent deviation(Connor)[4], canonical action attestation(CAVA)[5], description-code 불일치[6]를 다룬다. 본 연구는 새 시스템의 우월성을 주장하기보다, 독립 receipt에 적용한 동결 값-의미 계약이 어디까지 탐지하고 어디서 실패하는지를 측정한다. 국내 위협분류·CVE·가상화 연구[8-10]와 달리 정상 응답 뒤 외부효과를 ground truth로 삼는다.'),P('기여는 세 가지다. (1) 반복을 1,008개 의미 조건으로 묶은 cluster 통계, (2) 센서 양성대조군과 외부-schema hold-out을 통한 관측범위 분리, (3) 간접참조·저유병률·observer 지연이라는 실패 경계의 정량화다.'),
 P('2. 위협모델과 측정 방법','H'),P('공격자는 MCP 서버 구현·조건분기·반환 JSON을 통제한다. 방어자는 승인 입력, correlation ID, 계약 및 공격자와 행정·저장·권한 경계가 분리된 observer receipt를 본다. 계약은 값 보존, 효과 수, effect kind, tenant/path/sink 범위를 검사한다. downstream API까지 공격자가 통제하면 그 API의 자기서명 receipt는 독립 증거가 아니며 본 방어 가정은 성립하지 않는다.'),table([['독립 observer가 성립하는 배치','성립하지 않는 배치'],['은행/클라우드 감사로그처럼 별도 계정·불변 저장소','MCP 서버가 직접 작성하는 SQLite/응답'],['호출자가 검증하는 provider 서명+tenant binding','공격 서버와 동일 키·동일 관리자'],['2개 출처 교차검증 또는 투명성 로그','downstream API까지 공격자가 단독 통제']],[83*mm,83*mm]),P('실험의 로컬 SQLite는 독립 프로세스·저장소 경계를 재현할 뿐 실제 SaaS 독립성을 증명하지 않는다. 따라서 상용 SaaS 배치 가능성은 주장하지 않는다.'),PageBreak(),
 P('3. 실험 설계','H'),P('본실험 47,160행은 12도구×6공격×변형으로 구성되지만 모델·반복이 중첩된 1,008개 의미 조건이다. ITT는 실행 오류를 공격 FN/정상 FP로 포함하며 cluster bootstrap 95% CI를 쓴다. 외부 hold-out은 공식 filesystem·memory·everything의 6개 schema와 계약을 결과 확인 전에 동결해 10,080회를 실행했다. 공격 5계열 중 간접참조 1계열만 계약 미지였다.'),P('0인 비교군이 실제 구현됐는지 확인하려고 관측면별 perturbation 8종과 정상 1종을 6도구×100변형에 주입한 센서 양성대조군 5,400회를 별도로 실행했다. 이는 본 위협모델 성능이 아니라 detector wiring 검증이다.'),Image(f1,width=168*mm,height=58*mm),P('그림 1. 양성대조군에서는 manifest/response/attestation도 Recall 0.125, trajectory 0.250을 보였다. 본 공격에서 0인 이유는 공격이 그 관측면을 고정했기 때문이다. 반면 hold-out의 kind/cardinality 변조로 Trajectory-lite가 0→0.59가 된 것은 두 corpus의 공격 구성이 질적으로 다름을 뜻한다.','Cap'),
 P('4. 결과: 집계보다 계열별 실패','H'),table([['원본 ITT','TP','FN','FP','TN','F1 [cluster 95% CI]'],['v1',v1['tp'],v1['fn'],v1['fp'],v1['tn'],f"{v1['f1']:.4f} [{v1['cluster']['f1_ci95'][0]:.4f},{v1['cluster']['f1_ci95'][1]:.4f}]"],['v2',v2['tp'],v2['fn'],v2['fp'],v2['tn'],f"{v2['f1']:.4f} [{v2['cluster']['f1_ci95'][0]:.4f},{v2['cluster']['f1_ci95'][1]:.4f}]"],['hold-out frozen',5668,1532,38,2842,f"{eh['defenses']['toolproof_frozen']['f1']:.4f} [{eh['defenses']['toolproof_frozen']['cluster']['f1_ci95'][0]:.4f},{eh['defenses']['toolproof_frozen']['cluster']['f1_ci95'][1]:.4f}]" ]],[27*mm,15*mm,15*mm,15*mm,15*mm,80*mm]),P('표 1. ITT 혼동행렬. v2-v1 조건 평균 정확도 차이 CI [-0.000116, 0.001620]는 0을 포함한다.','Cap'),Image(f2,width=168*mm,height=51*mm),P('그림 2. direct target을 포함한 알려진 계열에서는 동결 계약이 탐지하지만 indirect_reference_resolution은 직접 receipt 필드를 보존한 채 resolved_target만 바꾸어 Recall≈0이다. 5계열 중 미지 계열이 하나뿐이므로 aggregate F1 0.8784는 일반화 증거가 아니라 “4계열 탐지·1계열 실패”의 요약이다.','Cap'),PageBreak(),
 P('4.1 Learned relation과 동결 계약의 동률','H2'),P('hold-out에서 learned relation과 frozen contract의 Recall(0.787), F1(0.878)이 동일했다. 이는 직접값 동등관계만 필요한 평가에서는 수작업 계약이 추가 탐지 이득을 주지 못했음을 뜻한다. Frozen contract의 별도 이점은 양성대조군의 schema_incomplete 600건을 추가 탐지하고 정책을 감사 가능한 명세로 남긴 점이다. 반대로 두 방법 모두 간접참조를 놓쳤으므로 이점은 행동 일반화가 아니라 schema completeness와 거버넌스에 한정된다.'),
 P('4.2 운영 유병률·지연','H2'),Image(f3,width=168*mm,height=51*mm),P('그림 3. 공격:정상=1:999에서 v1/v2 F1은 0.724/0.264, 예상 경보는 약 175/655건/10만 호출이다. 따라서 v2는 우월판이 아니라 고위험 도구의 고재현율 옵션이다.','Cap'),table([['사전 게이트','관측','판정'],['무방어 ASR ≥.40','0.9976','통과'],['F1/Recall/FPR','v1 .9979/.9960/.0008; v2 .9985/.9976/.0056','통과'],['Utility 감소 ≤.05p','차단 없는 사후탐지 구성','판정 보류'],['p95 ≤200ms','계약 .036ms; receipt 301.7ms','종단 실패'],['hold-out F1 ≥.75','.8784','통과(계열 n=1 한계)']],[53*mm,82*mm,31*mm]),P('표 2. 사전등록 게이트. 차단하지 않아 Utility 감소 0p인 구성은 방어 효용을 증명하지 않으므로 보류한다.','Cap'),
 P('5. 타당성 위협과 배치 조건','H'),P('공격·계약 공동설계, 미지 공격계열 n=1, 축약 비교군, 합성 효과와 로컬 observer가 외적 타당성을 제한한다. Connor-lite는 Connor[4]의 학습형 intent-deviation을, attestation-lite는 CAVA[5] 원 구현을 재현하지 않으므로 원 시스템 대비 우월성을 주장하지 않는다. 실제 배치는 provider와 MCP 서버의 관리자·키·저장소를 분리하고 receipt에 최종 resolved principal, redirect chain, tenant와 nonce를 결합해야 한다. 이 조건이 없으면 observer는 공격자의 두 번째 응답일 뿐이다.'),
 P('6. 결론','H'),P('동결 값-의미 계약은 직접 필드·효과 종류·개수 변조에는 유효하지만 간접참조에는 구조적으로 무력했다. 정상값 관계를 학습한 단순 baseline과의 동률은 수작업 계약의 탐지 이득이 제한됨을 보였다. 저유병률에서는 FPR이 F1보다 배치를 결정한다. 따라서 후속 연구는 제3자 작성 공격 다계열과 독립 provider receipt에서 이 경계를 재측정해야 한다.'),
 P('참고문헌','H'),P('[1] Model Context Protocol, “Tools; Security Best Practices,” 2026.<br/>[2] Z. Wang et al., “MCPTox,” AAAI 40(42), 35811-35819, 2026.<br/>[3] S. Yergattikar, “Securing the Tool Layer,” ACL Industry, 2026.<br/>[4] Huang et al., “From Component Manipulation to System Compromise: Understanding and Detecting Malicious MCP Servers,” arXiv:2604.01905, 2026.<br/>[5] Z. Wang, “CAVA: Canonical Action Verification and Attestation for Runtime Governance of Agentic AI Systems,” arXiv:2607.13716, 2026.<br/>[6] Y. Shi et al., “Description-Code Inconsistency in Real-world MCP Servers,” arXiv:2606.04769, 2026.<br/>[7] Z. Li et al., “Confused Deputy Attack Against Model Context Protocol,” ACM TOSEM, doi:10.1145/3830467, 2026.<br/>[8] 김찬형·이브라히모바 나일라 외, “MCP 기반 LLM 보안 위협 변화 동향 분석,” ASK, p.375, 2026.<br/>[9] 남장우 외, “공개 MCP 취약점 교차매핑 기반 공격사례 분석,” ASK, p.251, 2026.<br/>[10] 김도영·고남현 외, “VAT 기반 LLM 에이전트 하이브리드 보안 아키텍처,” ASK, p.310, 2026.','T')]
 SimpleDocTemplate(str(PAPER),pagesize=A4,leftMargin=15*mm,rightMargin=15*mm,topMargin=8*mm,bottomMargin=9*mm,title='MCP semantic contract measurement').build(story,onFirstPage=footer,onLaterPages=footer);print(PAPER)
if __name__=='__main__':main()
