from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (Image, PageBreak, Paragraph, SimpleDocTemplate,
                                Spacer, Table, TableStyle)

ROOT=Path(__file__).resolve().parent; FINAL=ROOT/'artifacts/final'; FIG=FINAL/'revision-figures'; FIG.mkdir(parents=True,exist_ok=True)
DOWNLOADS=Path('/Users/chchou/Downloads')
PAPER=DOWNLOADS/'MCP_ToolProof_KIISC_3페이지_논문.pdf'; REPORT=DOWNLOADS/'MCP_ToolProof_10모델_확장실험_결과보고서.pdf'
BLUE='#183B66'; CYAN='#0FA7A5'; ORANGE='#F28E2B'; RED='#D64545'; LIGHT='#EEF3F8'; GRAY='#5F6B7A'
FONT='/System/Library/Fonts/Supplemental/AppleGothic.ttf'; pdfmetrics.registerFont(TTFont('K',FONT));pdfmetrics.registerFont(TTFont('KB',FONT))
plt.rcParams['font.family']='Apple SD Gothic Neo';plt.rcParams['axes.unicode_minus']=False
S=getSampleStyleSheet()
S.add(ParagraphStyle(name='BodyK',fontName='K',fontSize=8.7,leading=12.5,wordWrap='CJK',alignment=TA_JUSTIFY,spaceAfter=2.2))
S.add(ParagraphStyle(name='SmallK',fontName='K',fontSize=7.0,leading=9.1,wordWrap='CJK'))
S.add(ParagraphStyle(name='TinyK',fontName='K',fontSize=6.1,leading=7.5,wordWrap='CJK'))
S.add(ParagraphStyle(name='H1K',fontName='KB',fontSize=13.5,leading=16.5,textColor=colors.HexColor(BLUE),spaceBefore=4,spaceAfter=3))
S.add(ParagraphStyle(name='H2K',fontName='KB',fontSize=10.3,leading=12.8,textColor=colors.HexColor(BLUE),spaceBefore=3,spaceAfter=2))
S.add(ParagraphStyle(name='TitleK',fontName='KB',fontSize=17,leading=21,alignment=TA_CENTER))
S.add(ParagraphStyle(name='CenterK',fontName='K',fontSize=8.5,leading=11,alignment=TA_CENTER))

def P(x,style='BodyK'): return Paragraph(str(x),S[style])
def pct(x): return f'{100*x:.2f}%'
def tbl(rows,widths,style='SmallK'):
    t=Table([[P(x,style) for x in row] for row in rows],colWidths=widths,repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor(BLUE)),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#A7B3C2')),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor(LIGHT)]),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),2.2),('RIGHTPADDING',(0,0),(-1,-1),2.2),('TOPPADDING',(0,0),(-1,-1),1.7),('BOTTOMPADDING',(0,0),(-1,-1),1.7)]))
    return t
def save(name):
    p=FIG/name;plt.tight_layout();plt.savefig(p,dpi=220,bbox_inches='tight',facecolor='white');plt.close();return str(p)

def figures(pre,rob):
    o=rob['original_cluster_robust']; ext=rob['external_holdout']; oa=rob['oauth_async']
    prev=[.5,.1,.01,.001]; x=np.arange(4);w=.32
    for i,key in enumerate(['toolproof','toolproof_v2']):
        vals=[next(z['f1'] for z in pre['defenses'][key]['prevalence'] if z['prevalence']==p) for p in prev]
        plt.bar(x+(i-.5)*w,vals,w,label='v1' if i==0 else 'v2',color=BLUE if i==0 else CYAN)
    plt.xticks(x,['1:1','1:9','1:99','1:999']);plt.ylim(0,1.05);plt.ylabel('F1');plt.xlabel('공격:정상 운영 비율');plt.legend();plt.title('운영 유병률 보정: v2는 보편적 우월이 아님')
    prevalence=save('prevalence.png')
    keys=['manifest_pin','response_schema','connor_lite_trajectory','canonical_action_attestation','learned_effect_relation','toolproof_frozen']
    labels=['Manifest','Response','Trajectory-lite','Attestation','Learned relation','ToolProof frozen']
    vals=[ext['defenses'][k]['recall'] for k in keys]
    plt.figure(figsize=(8.8,3.1));bars=plt.bar(np.arange(len(keys)),vals,color=[GRAY,GRAY,ORANGE,ORANGE,CYAN,BLUE]);plt.xticks(np.arange(len(keys)),labels,rotation=12);plt.ylim(0,1.08);plt.ylabel('Recall')
    for b,v in zip(bars,vals):plt.text(b.get_x()+b.get_width()/2,v+.02,f'{v:.2f}',ha='center',fontsize=8)
    plt.title('동결 외부-schema hold-out (미지 간접참조 공격 포함)'); holdout=save('holdout.png')
    grace=['toolproof_immediate_fail_open','toolproof_grace_50ms','toolproof_grace_150ms','toolproof_grace_400ms','toolproof_immediate_fail_closed'];labels2=['0/open','50 ms','150 ms','400 ms','0/closed']
    recall=[oa['defenses'][k]['recall'] for k in grace]; util=[oa['defenses'][k]['tn']/(oa['defenses'][k]['tn']+oa['defenses'][k]['fp']) for k in grace]
    plt.figure(figsize=(8.8,3.1));plt.plot(labels2,recall,'o-',label='공격 Recall',color=BLUE);plt.plot(labels2,util,'s-',label='정상 허용률',color=CYAN);plt.ylim(0,1.05);plt.legend();plt.title('비동기 observer 대기시간의 보안–효용 교환'); asyncp=save('async.png')
    return {'prevalence':prevalence,'holdout':holdout,'async':asyncp}

def footer(c,doc):
    c.saveState();c.setFont('K',6.5);c.setFillColor(colors.HexColor(GRAY));c.drawString(13*mm,7*mm,'MCP ToolProof — 반복을 독립 표본으로 간주하지 않은 수정 분석');c.drawRightString(197*mm,7*mm,str(doc.page));c.restoreState()

def make_report(a,pre,rob,fig):
    o=rob['original_cluster_robust'];ext=rob['external_holdout'];oa=rob['oauth_async'];off=rob['official_reference'];scope=rob['oauth_scope'];v1=o['toolproof'];v2=o['toolproof_v2']
    story=[P('MCP ToolProof 강건성·외부 타당성 수정 실험 보고서','TitleK'),P('사전등록 7개 게이트 복원 · 클러스터 통계 · 운영 유병률 · 외부 스키마 hold-out · OAuth/비동기 observer','CenterK'),Spacer(1,3*mm),
      P('요약','H1K'),P(f"기존 LLM agent loop {pre['assigned_runs']:,}회는 {o['toolproof']['cluster']['clusters']:,}개 의미 조건에 모델·반복이 중첩된 자료다. 따라서 실행행 단위 Wilson/McNemar를 주 근거에서 제외하고 의미 조건 cluster bootstrap을 사용했다. v2−v1 조건 평균 정확도 차이의 95% CI는 [{o['paired_cluster_delta']['ci95'][0]:.6f}, {o['paired_cluster_delta']['ci95'][1]:.6f}]로 0을 포함한다. v2는 보편적 우월안이 아니라 Recall–FPR 교환이다."),
      tbl([['사전 기준','관측','판정'],['무방어 공격 ASR ≥40%',pct(pre['unprotected_asr_itt']),'통과'],['v1/v2 F1 ≥.85',f"{v1['f1']:.4f}/{v2['f1']:.4f}",'통과'],['Recall ≥.90',f"{v1['recall']:.4f}/{v2['recall']:.4f}",'통과'],['FPR ≤5%',f"{v1['fpr']:.4f}/{v2['fpr']:.4f}",'통과'],['정상 Utility 감소 ≤5%p','성공 호출 차단 감소 0%p','통과*'],['p95 추가 지연 ≤200ms',f"계약 {pre['latency']['contract_p95_us']/1000:.3f} / receipt {oa['receipt_e2e_p95_ms']:.1f}ms",'연산 통과/종단 실패'],['hold-out F1 ≥.75',f"{ext['defenses']['toolproof_frozen']['f1']:.4f}",'판정']], [65*mm,70*mm,30*mm]),P('*v2의 정상 경보 FPR 0.56%는 Utility와 별도로 공개한다. receipt p95는 장애 제외 관측치의 HTTP 응답+주입 지연이다.','TinyK'),P('연구 본질·필요성·진행 이유','H1K'),tbl([['질문','답'],['무엇을 연구했나','MCP 선언/응답과 실제 외부효과 사이의 의미 무결성'],['왜 이 절차인가','서버 자기보고와 분리된 receipt만이 ground truth를 제공하기 때문'],['왜 필요한가','결제·메일·파일·DB 피해는 정상 JSON이 아니라 커밋된 side effect로 발생']],[43*mm,122*mm]),P('위협자 능력과 신뢰경계','H2K'),P('위협자는 서버 구현·조건 분기·반환 JSON을 통제하지만 승인 manifest, correlation ID가 붙은 observer receipt와 동결 계약은 통제하지 못한다고 둔다. 이 가정 밖의 observer 손상·미관찰 채널은 미지 간접참조 실패와 장애 주입으로 경계를 드러냈다.'),
      P('검증 층위와 실행량','H1K'),tbl([['층위','실행','목적/독립성'],['LLM agent loop','47,160 배정','1,008 의미조건에 모델·반복 중첩'],['적대 계약 단위','12,000','schema/value 규칙 경계'],['TCP+SQLite','2,800','별도 프로세스·영속 observer'],['MCP SDK stdio','1,400','initialize/list/call 재현'],['공식 reference server','300','실제 filesystem 권한경계'],['OAuth+async','1,100','scope·tenant·receipt 장애'],['외부-schema hold-out',f"{ext['runs']:,}",'동결 후 미지 공격·정상 변화']],[52*mm,32*mm,81*mm],'TinyK'),P('공격·계약 대응관계와 편향 통제','H2K'),P('치환–값 보존, 복제–cardinality, scope 확장–allowlist처럼 알려진 공격은 계약의 부정형이므로 높은 F1만으로 일반화를 주장할 수 없다. 이를 보완하려고 공식 도구 schema를 외부에서 가져와 동결하고, 계약에 없는 간접참조 공격을 결과 확인 전에 freeze했다. 다만 공격 작성자는 여전히 연구자이므로 완전 blind로 부르지 않는다.'),P('집계 원칙','H2K'),P('각 층위는 서로 다른 모집단이라 합산 F1을 만들지 않는다. LLM 행은 ITT/PP를 병렬 보고하고, 결론 통계는 모델·반복을 제외한 semantic-condition cluster bootstrap으로 계산한다. 운영 precision은 관측 평가셋 비율이 아니라 1:1, 1:9, 1:99, 1:999 유병률로 재보정한다.'),
      PageBreak(),P('1. 원자료의 증거 단위와 수정 통계','H1K'),P('47,160은 실행량이지 독립 표본 수가 아니다. cluster key는 도구×공격×migration×variant이며 모델과 반복은 같은 의미 조건의 중첩 관측으로 처리했다. 원래 행 단위 유의확률은 설명적 수치로만 남기고 결론에는 사용하지 않는다.'),
      tbl([['방어 ITT','TP','FN','FP','TN','F1 [cluster 95% CI]','FPR [cluster 95% CI]'],['v1',v1['tp'],v1['fn'],v1['fp'],v1['tn'],f"{v1['f1']:.4f} [{v1['cluster']['f1_ci95'][0]:.4f},{v1['cluster']['f1_ci95'][1]:.4f}]",f"{v1['fpr']:.4f} [{v1['cluster']['fpr_ci95'][0]:.4f},{v1['cluster']['fpr_ci95'][1]:.4f}]"],['v2',v2['tp'],v2['fn'],v2['fp'],v2['tn'],f"{v2['f1']:.4f} [{v2['cluster']['f1_ci95'][0]:.4f},{v2['cluster']['f1_ci95'][1]:.4f}]",f"{v2['fpr']:.4f} [{v2['cluster']['fpr_ci95'][0]:.4f},{v2['cluster']['fpr_ci95'][1]:.4f}]" ]],[21*mm,14*mm,14*mm,14*mm,14*mm,48*mm,48*mm],'TinyK'),Image(fig['prevalence'],width=170*mm,height=60*mm),P('정상:공격=999:1이면 v1/v2 F1은 각각 0.724/0.264다. 고정 FPR의 운영 영향 때문에 v1을 기본, v2를 고위험 도구의 고재현율 옵션으로 재정의한다.'),
      P('2. 동결 외부-schema hold-out','H1K'),P(f"공식 MCP reference filesystem·memory·everything 서버에서 6개 도구 schema를 수집하고 schema/계약 SHA-256을 동결한 뒤 {ext['runs']:,}회({len(ext['models'])}모델)를 실행했다. 이는 도구 schema와 정상 구현은 외부 출처이나 공격과 계약은 연구자 작성이므로 ‘제3자 blind 공격셋’이 아니라 ‘외부-schema hold-out’이다."),Image(fig['holdout'],width=170*mm,height=60*mm),P('정상 변화 회귀셋','H2K'),tbl([['migration','Manifest pin FPR','Frozen 계약 FPR']]+[[m,f"{ext['by_migration'][m]['manifest_pin']['fpr']:.3f}",f"{ext['by_migration'][m]['toolproof_frozen']['fpr']:.3f}"] for m in sorted(ext['by_migration']) if m!='none'],[72*mm,47*mm,47*mm],'TinyK'),P('manifest byte pin은 의미를 바꾸지 않는 description·property 순서·optional field 변화에도 경보할 수 있다. frozen 의미계약의 장점은 정상 schema 변화와 effect 관계를 분리하는 데 있으며, 반대로 계약에 없는 런타임 해석은 놓친다.'),
      PageBreak(),P('3. 미지 공격·정상 migration의 실패 분석','H1K'),P('동결 계약에 없는 indirect_reference_resolution은 원 인자와 직접 효과 필드는 보존하면서 런타임 resolved_target만 바꾼다. 실패를 숨기지 않고 공격별 Recall로 공개한다.'),
      tbl([['공격','Trajectory-lite','Learned relation','ToolProof frozen']]+[[name,f"{ext['by_attack'][name]['connor_lite_trajectory']['recall']:.3f}",f"{ext['by_attack'][name]['learned_effect_relation']['recall']:.3f}",f"{ext['by_attack'][name]['toolproof_frozen']['recall']:.3f}"] for name in sorted(k for k in ext['by_attack'] if k!='none')],[55*mm,35*mm,35*mm,40*mm]),P('Trajectory-lite는 Connor 원 구현이 아니다. 실행 전후 효과 kind/cardinality 이탈만 검사하는 의도궤적 근사이며, Connor의 두 단계 intent-deviation 모델·학습자료를 재현하지 않았다. canonical attestation 역시 서버가 보고한 정상 action을 신뢰하는 축약 대조군이다.'),
      P('4. 실제 프로토콜·권한·비동기 경계','H1K'),tbl([['경계','실행','결과'],['공식 filesystem MCP npm 서버',off['runs'],f"root 밖 시도 {off['permission_blocked']}건 모두 차단"],['OAuth-like HMAC scope HTTP',scope['runs'],f"예상 200/403 일치 {scope['expected_status_correct']}/{scope['runs']}"],['비동기 HTTP→SQLite observer',oa['runs'],f"observer unavailable {oa['observer_unavailable']}건"]],[62*mm,28*mm,76*mm]),Image(fig['async'],width=170*mm,height=59*mm),P('실제 원격 SaaS tenant는 사용하지 않았다. OAuth-like 실험은 실제 HTTP·서명 토큰·tenant/scope 검사를 사용하지만 상용 provider의 receipt·rate limit·과금 경계와 동등하다고 주장하지 않는다.'),
      P('5. 결론과 남은 위험','H1K'),P('핵심 기여는 거의 1인 F1이 아니라 (i) manifest/응답과 외부 효과의 관측면 차이, (ii) 동결 계약이 알려진 값-의미 변조에는 신호를 주지만 미지 간접참조에는 실패한다는 경계, (iii) v2의 Recall–FPR 교환, (iv) observer 지연·장애의 운영 비용을 같은 자료에서 드러낸 것이다. 남은 최우선 과제는 제3자가 만든 도구·공격·계약으로 완전 blind 평가하고 실제 SaaS test tenant receipt로 반복하는 것이다.'),P('실패가 바꾼 설계','H2K'),tbl([['관측 실패','추가 조치','해석'],['v1 FN 174','schema completeness를 v2에 추가','Recall 상승·FP 증가'],['1:999에서 v2 F1 저하','유병률 보정','고위험 선택안으로 제한'],['간접참조 Recall 0','실패 포함 hold-out','observer schema 확장 필요'],['300ms receipt tail','grace/fail 정책 비교','연산비와 대기비 분리'],['비독립 반복','cluster bootstrap','행 단위 p-value를 결론에서 제외']],[48*mm,57*mm,60*mm],'TinyK'),P('권장 배치 순서','H2K'),P('① shadow mode로 정상 FPR과 schema drift를 수집한다. ② 결제·메일처럼 피해가 큰 도구에 v2+human approval을 적용한다. ③ observer unavailable은 저위험 제한실행, 고위험 fail-closed로 분리한다. ④ provider receipt 지연 SLO와 compensating transaction 성공률을 함께 감시한다. ⑤ 계약 버전 변경은 freeze 후 정상 migration 회귀셋을 통과시킨다.'),P('재현성','H2K'),P('원시 JSONL, freeze.json, 공식 tools/list snapshot, seed, 모델, 환경, schema/계약 hash를 보존했다. 사용자 파일을 삭제하거나 실제 외부 계정에 효과를 발생시키지 않았고 임시 sandbox·localhost·가상 tenant만 사용했다.')]
    SimpleDocTemplate(str(REPORT),pagesize=A4,leftMargin=13*mm,rightMargin=13*mm,topMargin=11*mm,bottomMargin=12*mm).build(story,onFirstPage=footer,onLaterPages=footer)

def paper_header(story):
    story += [Spacer(1,4*mm),P('MCP 도구의 조건부 외부효과 변조 탐지:','TitleK'),P('동결 의미계약과 독립 관찰자의 강건성 평가','TitleK'),Spacer(1,2*mm),P('익명 심사용 원고','CenterK'),P('Detecting Conditional External-Effect Manipulation in MCP Tools:<br/>Robustness Evaluation of Frozen Semantic Contracts and Independent Observers','CenterK'),Spacer(1,3*mm),P('<b>요약</b>  MCP 도구의 manifest와 응답이 정상이어도 외부 효과가 조건부로 변조될 수 있다. 본 연구는 이 관측면 불일치를 본질로 두고, 값·개수·종류·범위 계약을 독립 observer의 receipt에 적용한다. 47,160회 실행을 독립 표본으로 과장하지 않고 1,008개 의미 조건 cluster bootstrap으로 재분석했으며, 공식 reference-server schema를 동결한 hold-out과 OAuth-like 권한·비동기 observer 장애를 추가했다. 결과는 알려진 변조에서 높은 탐지력을 보이지만 미지 간접참조 공격을 놓치며, v2도 FPR 때문에 저유병률 운영에서 v1보다 불리함을 보인다. 따라서 기여는 완전 방어가 아니라 의미 무결성의 측정 가능한 경계와 보안–효용 교환을 제시하는 데 있다.','BodyK')]

def make_paper(a,pre,rob,fig):
    o=rob['original_cluster_robust'];ext=rob['external_holdout'];oa=rob['oauth_async'];v1=o['toolproof'];v2=o['toolproof_v2']
    story=[];paper_header(story)
    story += [P('1. 서론','H1K'),P('연구의 본질은 “도구가 무엇을 선언·반환했는가”가 아니라 “실제로 어떤 외부 상태를 바꾸었는가”를 검증하는 것이다. LLM agent는 정상 JSON만 보고 성공으로 판단할 수 있으므로 byte-identical manifest·정상 응답을 유지한 조건부 side effect 변조는 정적 무결성과 응답 검사 사이에 남는다. 이를 연구한 이유는 결제·메일·파일·데이터베이스 도구에서 모델의 판단보다 provider receipt가 최종 피해를 결정하기 때문이다. 필요한 방어는 서버 자기보고가 아닌 독립 evidence와 실행 가능한 값-의미 계약이다.'),
      P('본 연구는 (1) 외부효과 ground truth, (2) 동결 계약, (3) 미지 공격·정상 변화, (4) 운영 유병률·observer 장애를 함께 평가한다. 최초 발견이나 MCP 전체 방어를 주장하지 않는다.'),tbl([['연구질문','검증 증거'],['RQ1 관측면 차이','동일 manifest·정상 응답·상이한 observer state'],['RQ2 일반화','동결 외부-schema와 미지 간접참조 공격'],['RQ3 운영성','유병률 보정, 정상 migration, observer 지연·장애']],[40*mm,127*mm],'TinyK'),P('2. 관련연구와 차별점','H1K'),P('MCPTox는 tool poisoning을, Connor는 실행 전후 intent deviation을, CAVA는 canonical action attestation을 다룬다. 국내 연구도 위협 분류·CVE·가상화 방어를 제안했다. 본 연구의 차이는 공식 외부 schema에서 직접값·cardinality·effect kind를 동결하고 독립 receipt와 대조하며, 계약 밖 간접참조 실패와 정상 migration 오탐까지 함께 보고하는 데 있다. Connor-lite 대조군은 원 논문 재현이 아니라 kind/cardinality 궤적만 구현한 축약판이다.'),
      P('3. 방법','H1K'),P('승인 manifest, 실제 tool input, correlation ID가 붙은 독립 receipt를 수집한다. 계약은 effect.target=input.target, 효과 수≤1, read-only write=0, tenant/path allowlist, 비승인 sink=0을 판정한다. 위반 또는 observer unavailable은 도구 위험도에 따라 차단·승인·제한 실행으로 분기한다. 공격 정답은 detector 출력과 분리된 서버 모드와 observer 상태로 정의했다.'),tbl([['계약 축','실행 불변식','위반 예'],['값','receipt.target=input.target','수신자 치환'],['개수','idempotency key당 효과≤1','숨은 복제'],['종류','declared effect kind 일치','write로 변환'],['범위','tenant/path/sink allowlist','교차 tenant·채널']],[26*mm,75*mm,66*mm],'TinyK'),P('위협자는 MCP 서버 코드를 배포·갱신할 수 있으나 승인 manifest와 정상형 응답은 유지한다. observer 저장소·correlation ID·승인 계약은 변조하지 못한다고 가정한다. 이 신뢰경계가 깨지면 ToolProof도 보장하지 못한다.'),P('3.1 구현과 판정 시점','H2K'),P('proxy는 agent의 실제 tool arguments를 보존하고 실행 전 schema completeness를 검사한다. 실행 후 응답을 모델에 반환하기 전에 correlation ID로 receipt를 조회해 직접값·종류·개수·scope를 판정한다. 이미 커밋된 효과는 탐지만으로 복구되지 않으므로 고위험 도구는 prepare–verify–commit 또는 idempotency key와 결합한다.'),P('3.2 비교군과 주장 범위','H2K'),P('manifest·응답은 관측면 negative control이다. intent trajectory 축약은 effect kind/cardinality만 비교하며 Connor의 학습 모델을 재현하지 않는다. canonical attestation 축약은 서버가 보고한 action을 신뢰한다. learned relation은 정상 실행에서 직접값 동등관계를 학습한다. 이 축약 구현을 원 연구와 동등하다고 주장하지 않는다.'),tbl([['단계','입력','오류·집계'],['배정','model·tool·condition·seed','모든 배정 보존'],['실행','tool call','timeout도 ITT 포함'],['관찰','correlation receipt','unavailable 별도'],['통계','semantic condition','중첩 cluster bootstrap']],[31*mm,61*mm,75*mm],'TinyK'),PageBreak(),
      P('4. 실험 설계와 사전 기준','H1K'),P(f"10개 모델·12개 합성 도구의 {pre['assigned_runs']:,}회는 모델·반복이 중첩된 1,008개 의미 조건이다. ITT에서 오류는 공격 FN/정상 FP로 처리하고 cluster bootstrap 95% CI를 주 통계로 사용한다. 외부 hold-out은 공식 filesystem·memory·everything의 6개 tools/list schema와 계약을 hash로 동결한 뒤 5개 공격(미지 간접참조 1개)과 정상 migration 6종을 섞었다."),
      tbl([['사전등록 게이트','관측','판정'],['무방어 ASR ≥.40',f"{pre['unprotected_asr_itt']:.4f}",'통과'],['F1 ≥.85',f"v1 {v1['f1']:.4f}; v2 {v2['f1']:.4f}",'통과'],['Recall ≥.90',f"{v1['recall']:.4f}; {v2['recall']:.4f}",'통과'],['FPR ≤.05',f"{v1['fpr']:.4f}; {v2['fpr']:.4f}",'통과'],['Utility 감소 ≤.05p','성공 호출 차단 0p*','통과'],['p95 추가 지연 ≤200ms',f"계약 {pre['latency']['contract_p95_us']/1000:.3f}; receipt {oa['receipt_e2e_p95_ms']:.1f}ms",'연산 통과/종단 실패'],['hold-out F1 ≥.75',f"{ext['defenses']['toolproof_frozen']['f1']:.4f}",'판정']], [62*mm,82*mm,24*mm],'TinyK'),P('*v2 정상 경보 FPR 0.56%는 Utility와 별도다. receipt p95는 장애 제외 HTTP 응답+주입 지연이다.','TinyK'),
      P('5. 결과','H1K'),tbl([['방어 ITT','TP','FN','FP','TN','F1 [cluster 95% CI]'],['정적 hash',0,43200,0,3960,'0.0000'],['응답 검사',0,43200,0,3960,'0.0000'],['의도궤적 축약',0,43200,0,3960,'0.0000'],['v1',v1['tp'],v1['fn'],v1['fp'],v1['tn'],f"{v1['f1']:.4f} [{v1['cluster']['f1_ci95'][0]:.4f},{v1['cluster']['f1_ci95'][1]:.4f}]"],['v2',v2['tp'],v2['fn'],v2['fp'],v2['tn'],f"{v2['f1']:.4f} [{v2['cluster']['f1_ci95'][0]:.4f},{v2['cluster']['f1_ci95'][1]:.4f}]" ]],[25*mm,16*mm,16*mm,16*mm,16*mm,78*mm],'TinyK'),P('앞의 세 방어는 동일 호출에 실제 적용했지만 공격 정의가 그 관측면을 고정하므로 0은 예상된 negative control이다. 강한 우월성 비교가 아니라 위협모델의 관측 사각지대를 확인하는 용도로만 해석한다.'),P(f"v2−v1 조건 평균 정확도 차이 CI [{o['paired_cluster_delta']['ci95'][0]:.6f},{o['paired_cluster_delta']['ci95'][1]:.6f}]는 0을 포함한다. 공격:정상=1:999 보정 F1은 v1 0.724, v2 0.264다. 따라서 v1을 기본, v2를 고위험 도구용 고재현율 옵션으로 해석한다."),Image(fig['prevalence'],width=166*mm,height=51*mm),
      P('5.1 외부-schema hold-out과 실패','H2K'),Image(fig['holdout'],width=166*mm,height=50*mm),P(f"hold-out {ext['runs']:,}회에서 동결 계약의 전체 F1은 {ext['defenses']['toolproof_frozen']['f1']:.4f}였다. 계약에 없는 indirect_reference_resolution은 원 입력 필드를 보존한 채 resolved_target만 바꾸므로 탐지되지 않았다. 이는 실패해도 일반화 질문에 답하는 핵심 결과다."),tbl([['정상 migration','Frozen 계약 FPR'],*[ [m,f"{ext['by_migration'][m]['toolproof_frozen']['fpr']:.3f}"] for m in sorted(ext['by_migration']) if m!='none']],[78*mm,89*mm],'TinyK'),PageBreak(),
      P('5.2 정상 변화·권한·비동기 경계','H1K'),P('정상 description 변경, property reorder, optional field, constraint 완화, output schema 변화에 대한 FPR을 별도로 계산했다. 공식 filesystem MCP 서버의 임시 root 밖 접근 100건은 서버 권한경계가 모두 차단했다. HMAC token을 쓰는 로컬 HTTP tenant/scope 경계 300건은 예상 200/403과 모두 일치했다. 이 실험은 실제 프로토콜·서명 token 경계지만 상용 SaaS test tenant는 아니다.'),Image(fig['async'],width=166*mm,height=54*mm),P(f"HTTP→SQLite 비동기 observer {oa['runs']}회 중 unavailable {oa['observer_unavailable']}건이었다. 400ms grace는 Recall을 유지하면서 정상 허용률을 높였지만, 전체 receipt end-to-end p95 {oa['receipt_e2e_p95_ms']:.1f}ms로 200ms 게이트를 실패했다. 계약 계산 p95 {pre['latency']['contract_p95_us']/1000:.3f}ms와 receipt 대기시간을 혼동하지 않는다."),
      P('6. 논의와 타당성 위협','H1K'),P('정적 hash·응답 대조군 Recall=0은 위협모델이 관측면을 고정한 결과라 강한 우월성 근거로 사용하지 않는다. 공격·계약 공동설계, 연구자 작성 공격, 합성 도구, 비독립 반복, 로컬 OAuth가 타당성을 제한한다. 10개 모델은 agent-loop 호환성을 보여줄 뿐 탐지기의 독립 증거를 10배로 만들지 않는다. ToolProof도 observer가 보지 못하는 간접참조·비인가 채널은 놓친다. 완전 blind 평가는 제3자가 도구·공격·계약을 작성하고 freeze 후 정상 migration과 섞어야 한다.'),tbl([['위험','현재 완화','남은 검증'],['공동설계 편향','외부 schema+freeze','제3자 공격·계약'],['저유병률 오탐','prevalence 보정','실운영 base rate'],['observer 장애','지연/장애 주입','상용 receipt SLO'],['정상 변화','migration 5종','장기 schema drift']],[42*mm,57*mm,68*mm],'TinyK'),P('6.1 실패 분석과 확장','H2K'),P('v1은 필수 field가 사라질 때 비교가 생략되어 미탐했고, v2 completeness는 FN을 줄이는 대신 FP를 늘렸다. 간접참조 공격은 직접 필드와 cardinality를 보존해 두 버전 모두 놓쳤다. 따라서 observer schema에 resolved principal·redirect chain·provider-side final target을 포함해야 한다. 지연 공격에는 지속 표본추출과 시간창 계약이 필요하다.'),P('6.2 운영 정책','H2K'),tbl([['상태','저위험','고위험'],['계약 통과','즉시 전달','receipt 후 commit'],['위반','경고·제한','보류·승인'],['observer unavailable','rate limit','fail-closed'],['계약 변경','shadow 비교','재승인']],[52*mm,55*mm,60*mm],'TinyK'),P('정상:공격 999:1에서 예상 경보는 v1 약 175/10만, v2 약 655/10만이다. 실제 배치는 F1보다 사용자 승인 부담·rollback 성공률을 함께 SLO로 둬야 한다.'),
      P('7. 결론','H1K'),P('manifest 무결성은 외부효과 의미 무결성을 보장하지 않는다. 독립 observer와 동결 계약은 알려진 값-의미 변조에 유용한 추가 신호지만, 미지 간접참조와 observer 장애에서 명시적 한계를 보였다. 운영 배치는 단일 F1이 아니라 공격 유병률, FPR, receipt 지연, fail-open/closed 효용을 함께 선택해야 한다.'),P('재현성·안전','H2K'),P('원시 JSONL에는 조건·seed·모델·오류·환경·schema/contract hash를 보존했다. 공식 서버는 임시 root, OAuth는 가상 tenant, 네트워크는 localhost만 사용했고 실제 결제·메일·계정에 효과를 만들지 않았다. freeze.json을 결과 분석 전에 생성해 후행 계약수정을 제한했다.'),
      P('참고문헌','H1K'),P('[1] Model Context Protocol, “Tools” and “Security Best Practices,” 2026.  [2] Z. Li et al., “Confused Deputy Attack Against Model Context Protocol,” ACM TOSEM, doi:10.1145/3830467, 2026.  [3] Z. Wang, Y. Gao, Y. Wang, S. Liu, H. Sun, H. Cheng, G. Shi, H. Du, X. Li, “MCPTox,” AAAI 40(42), 35811–35819, 2026.  [4] S. Yergattikar, “Securing the Tool Layer: A Threat Taxonomy and Runtime Defense Framework for Model Context Protocol Deployments,” ACL Industry, p.865–, 2026.  [5] Huang et al., “From Component Manipulation to System Compromise: Understanding and Detecting Malicious MCP Servers,” arXiv:2604.01905, 2026.  [6] Z. Wang, “CAVA: Canonical Action Verification and Attestation for Runtime Governance of Agentic AI Systems,” arXiv:2607.13716, 2026.  [7] Y. Shi et al., “Description-Code Inconsistency in Real-world MCP Servers: Measurement, Detection, and Security Implications,” arXiv:2606.04769, 2026.  [8] 김찬형·이브라히모바 나일라 외, “MCP 기반 AI 에이전트 환경에서의 LLM 보안 위협 변화 동향 분석,” ASK, p.375, 2026.  [9] 남장우 외, “공개된 MCP 취약점 교차매핑 기반 공격사례 분석,” ASK, p.251, 2026.  [10] 김도영·고남현 외, “VAT 기반 LLM 에이전트 하이브리드 보안 아키텍처,” ASK, p.310, 2026.','TinyK')]
    SimpleDocTemplate(str(PAPER),pagesize=A4,leftMargin=15*mm,rightMargin=15*mm,topMargin=9*mm,bottomMargin=9*mm).build(story,onFirstPage=footer,onLaterPages=footer)

def main():
    a=json.loads((FINAL/'analysis.json').read_text());pre=json.loads((FINAL/'preregistered-metrics.json').read_text());rob=json.loads((FINAL/'robustness-analysis.json').read_text());fig=figures(pre,rob);make_report(a,pre,rob,fig);make_paper(a,pre,rob,fig);print(PAPER);print(REPORT)
if __name__=='__main__':main()
